security:
    password_hashers:
        App\Infrastructure\User\Security\SecurityUser: 'auto'

    providers:
        app_users:
            id: App\Infrastructure\User\Security\SecurityUserProvider

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        activation:
            pattern: ^/activate
            security: false

        admin:
            pattern: ^/admin
            provider: app_users
            form_login:
                login_path: admin_login
                check_path: admin_login
                default_target_path: admin
                enable_csrf: true
            logout:
                path: /admin/logout
                target: admin_login

        main:
            lazy: true

    role_hierarchy:
        ROLE_OWNER: ROLE_ADMIN
        ROLE_ADMIN: ROLE_SUPPORT

    access_control:
        - { path: ^/admin/login$, roles: PUBLIC_ACCESS }
        - { path: ^/admin, roles: ROLE_SUPPORT }

when@test:
    security:
        password_hashers:
            App\Infrastructure\User\Security\SecurityUser:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
